##Docker compose file for FURNISHAI-APP and Jenkings 

version: "1"

services:

  ml-app:
    image: furnishai-app:latest
    ports:
      - 8000:8000
  
  jenkins-server:
    image: jenkins/jenkins:latest
    ports:
      - 8081:8080


    

