##Docker compose file for FURNISHAI-APP and Jenkins 

services:

  ml-app:
    image: furnishai-app:latest
    container_name: final-project-ml-app
    ports:
      - "8000:8000"
    networks:
      - final-project_final-project
  
  jenkins-server:
    image: jenkins/jenkins:lts
    container_name: final-project-jenkins-server
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - final-project_final-project
    user: root

networks:
  final-project_final-project:
    driver: bridge

volumes:
  jenkins_home:
